CREATE TABLE IF NOT EXISTS opengrep_rules (
    id TEXT PRIMARY KEY,
    rule_id TEXT UNIQUE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sonarqube_rules (
    id TEXT PRIMARY KEY,
    rule_id TEXT UNIQUE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
