// Re-exported from @dockier/shared-types — do not define types here.
export type {
  Connection,
  Repo,
  TechBadgeInfo,
  RepoStats,
  RepoMember,
  FixResult,
  CommitInfo,
  RepoIssue,
  RepoPullRequest,
  DeployOption,
  DetectedServiceInfo,
  RepoAiAnalysis,
  SensitiveDataField,
  RepoVulnerability,
  RepoDependency,
  RepoAnalysisResponse,
  StackComponent,
  StackAnalysisResponse,
  SensitiveDataTableColumn,
  SensitiveDataTable,
  SensitiveDataAnalysis,
} from "@dockier/shared-types";
