/**
 * Frontend type barrel — re-exports from @dockier/shared-types.
 *
 * All domain types are defined in the shared package (packages/shared-types)
 * and re-exported here so existing import paths (`../types`) continue to work.
 */

export type {
  Project,
  ProjectSourceType,
  ProjectTemplate,
  ProjectConfig,
  ProjectSettings,
  Deployment,
  DeploymentStatus,
  DeployStrategy,
  Provider,
  ScanSummary,
  Scan,
  ScanStatus,
  Finding,
  FindingSeverity,
  ScanProgress,
  SecurityFindingCounts,
  ProviderSeverityCounts,
  Connection,
  Repo,
  TechBadgeInfo,
  RepoStats,
  RepoMember,
  FixResult,
  CommitInfo,
  RepoIssue,
  RepoPullRequest,
  DeployOption,
  DetectedServiceInfo,
  RepoAiAnalysis,
  SensitiveDataField,
  RepoVulnerability,
  RepoDependency,
  RepoAnalysisResponse,
  StackComponent,
  StackAnalysisResponse,
  SensitiveDataTableColumn,
  SensitiveDataTable,
  SensitiveDataAnalysis,
  PMIntegration,
  PMTeam,
  PMMember,
  PaginationMeta,
  BillingDetails,
} from "@dockier/shared-types";
