import type { ConnectionLike } from "./provider-client.js";

type CreateMergeRequestInput = {
  owner: string;
  repo: string;
  branch: string;
  filePath: string;
  startLine: number;
  endLine: number;
  severity: string;
  message: string;
  snippet: string;
  assignee?: string;
  reviewer?: string;
};

type MergeRequestResult = {
  mrUrl: string;
  mrId: string;
  mrTitle: string;
};

function baseUrl(connection: ConnectionLike): string {
  if (connection.provider === "github") return connection.endpoint || "https://api.github.com";
  if (connection.provider === "gitlab" || connection.provider === "gitlab_self_hosted") return connection.endpoint || "https://gitlab.com";
  return connection.endpoint || "https://api.bitbucket.org";
}

function webRepoUrl(connection: ConnectionLike, owner: string, repo: string): string {
  if (connection.provider === "github") return `https://github.com/${owner}/${repo}`;
  if (connection.provider === "gitlab" || connection.provider === "gitlab_self_hosted") return `${connection.endpoint || "https://gitlab.com"}/${owner}/${repo}`;
  return `https://bitbucket.org/${owner}/${repo}`;
}

function summarizeSeverity(severity: string): string {
  const normalized = severity.toLowerCase();
  if (normalized.includes("critical")) return "Critical";
  if (normalized.includes("high")) return "High";
  if (normalized.includes("medium")) return "Medium";
  if (normalized.includes("low")) return "Low";
  return "Info";
}

export function summarizeFindingTitle(input: Pick<CreateMergeRequestInput, "severity" | "message" | "filePath">): string {
  const trimmed = input.message.trim();
  const prefix = `[${summarizeSeverity(input.severity)}]`;
  const base = trimmed.length > 72 ? `${trimmed.slice(0, 69)}...` : trimmed;
  return `${prefix} ${base} (${input.filePath})`;
}

export function estimateFixMinutes(input: Pick<CreateMergeRequestInput, "severity" | "snippet" | "startLine" | "endLine">): number {
  const lineSpan = Math.max(1, input.endLine - input.startLine + 1);
  const snippetComplexity = Math.ceil(input.snippet.length / 180);
  const severityMultiplier = input.severity.toLowerCase().includes("critical")
    ? 2.2
    : input.severity.toLowerCase().includes("high")
      ? 1.8
      : input.severity.toLowerCase().includes("medium")
        ? 1.4
        : 1.1;
  return Math.max(10, Math.round((lineSpan * 2 + snippetComplexity * 6) * severityMultiplier));
}

function buildBody(input: CreateMergeRequestInput): string {
  return [
    "## Security finding context",
    `- File: \`${input.filePath}\``,
    `- Range: ${input.startLine}-${input.endLine}`,
    `- Severity: ${input.severity}`,
    "",
    "## Finding message",
    input.message,
    "",
    "## Code snippet",
    "```",
    input.snippet || "// snippet unavailable",
    "```",
    "",
    "This PR was generated by Dockier's Fastify restoration workflow.",
  ].join("\n");
}

export async function createMergeRequest(connection: ConnectionLike, input: CreateMergeRequestInput): Promise<MergeRequestResult> {
  const title = summarizeFindingTitle(input);
  if (connection.provider === "github") {
    const headers = {
      Authorization: `Bearer ${connection.personal_token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    };
    const origin = baseUrl(connection);
    const repoRes = await fetch(`${origin}/repos/${input.owner}/${input.repo}`, { headers });
    const repoInfo = repoRes.ok ? ((await repoRes.json()) as { default_branch?: string }) : { default_branch: "main" };
    const base = repoInfo.default_branch || "main";
    const createRes = await fetch(`${origin}/repos/${input.owner}/${input.repo}/pulls`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        title,
        head: input.branch,
        base,
        body: buildBody(input),
        draft: true,
      }),
    });

    if (createRes.ok) {
      const body = (await createRes.json()) as { html_url?: string; node_id?: string; number?: number };
      return {
        mrUrl: body.html_url || `${webRepoUrl(connection, input.owner, input.repo)}/pulls`,
        mrId: body.node_id || String(body.number || ""),
        mrTitle: title,
      };
    }

    return {
      mrUrl: `${webRepoUrl(connection, input.owner, input.repo)}/compare/${base}...${encodeURIComponent(input.branch)}`,
      mrId: "draft",
      mrTitle: title,
    };
  }

  if (connection.provider === "gitlab" || connection.provider === "gitlab_self_hosted") {
    const project = encodeURIComponent(`${input.owner}/${input.repo}`);
    const headers = { "PRIVATE-TOKEN": connection.personal_token, "Content-Type": "application/json" };
    const origin = baseUrl(connection);
    const projectRes = await fetch(`${origin}/api/v4/projects/${project}`, { headers: { "PRIVATE-TOKEN": connection.personal_token } });
    const projectInfo = projectRes.ok ? ((await projectRes.json()) as { default_branch?: string }) : { default_branch: "main" };
    const targetBranch = projectInfo.default_branch || "main";
    const response = await fetch(`${origin}/api/v4/projects/${project}/merge_requests`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        source_branch: input.branch,
        target_branch: targetBranch,
        title,
        description: buildBody(input),
        assignee_id: input.assignee ? Number(input.assignee) : undefined,
      }),
    });
    if (response.ok) {
      const body = (await response.json()) as { web_url?: string; iid?: number; id?: number };
      return {
        mrUrl: body.web_url || `${webRepoUrl(connection, input.owner, input.repo)}/-/merge_requests`,
        mrId: String(body.iid || body.id || ""),
        mrTitle: title,
      };
    }
    return {
      mrUrl: `${webRepoUrl(connection, input.owner, input.repo)}/-/merge_requests/new?merge_request[source_branch]=${encodeURIComponent(input.branch)}`,
      mrId: "draft",
      mrTitle: title,
    };
  }

  return {
    mrUrl: `${webRepoUrl(connection, input.owner, input.repo)}/pull-requests/new?source=${encodeURIComponent(input.branch)}`,
    mrId: "draft",
    mrTitle: title,
  };
}
