-- DEPRECATED — do not run this file.
--
-- This schema was written when the SAST workers were a standalone prototype.
-- Every table it created has since been superseded, and applying it against a
-- real Dockier database would create shadow tables that nothing reads:
--
--   security_scans   -> superseded by `scans` (supabase/migrations/0015_scans.sql)
--                       and `findings` (0016_findings.sql). Findings are stored
--                       as rows, not as a JSONB blob, so they can be queried,
--                       filtered and deduplicated.
--   pgboss.job       -> pg-boss owns and migrates its own schema. The hand-rolled
--                       DDL here omitted priority, retrylimit, singletonkey and
--                       partitioning, so it never matched the real thing.
--   rules,
--   tool_configurations -> superseded by `custom_rules` (0017_custom_rules.sql)
--                       and the rule-overrides table the backend already reads.
--
-- Still to be migrated properly (tracked in context/FIX-PLAN.md §6.1, Phase 4):
--   quality_profiles, quality_profile_rules, quality_gates — these have no
--   canonical equivalent yet and need real numbered migrations plus seeders.
--
-- Canonical schema lives in supabase/migrations/. Apply it with `pnpm db:migrate`.
