import { fetchRepoFile } from "../providers/provider-client.js";
import type { ConnectionLike } from "../providers/provider-client.js";
import { generateCodeFix } from "./ai-fix.js";
import { commitFixToBranch } from "./fix-branch.js";
import { DomainError } from "../../../../shared/supabase/errors.js";

type CreateMergeRequestInput = {
  owner: string;
  repo: string;
  branch: string;
  filePath: string;
  startLine: number;
  endLine: number;
  ruleId: string;
  severity: string;
  message: string;
  snippet: string;
  aiType?: string;
  assignee?: string;
  reviewer?: string;
};

type CreateMergeRequestOptions = {
  openAiApiKey?: string;
  openAiModel?: string;
};

type MergeRequestResult = {
  mrUrl: string;
  mrId: string;
  mrTitle: string;
};

export function parseRepoKey(repoKey: string): { owner: string; repo: string } {
  const parts = repoKey.split("/").filter(Boolean);
  if (parts.length < 2) {
    throw new DomainError(`Invalid repository key: ${repoKey}`, "bad_request");
  }
  const repo = parts[parts.length - 1]!;
  const owner = parts.slice(0, -1).join("/");
  return { owner, repo };
}

function baseUrl(connection: ConnectionLike): string {
  if (connection.provider === "github") return connection.endpoint || "https://api.github.com";
  if (connection.provider === "gitlab" || connection.provider === "gitlab_self_hosted") return connection.endpoint || "https://gitlab.com";
  return connection.endpoint || "https://api.bitbucket.org";
}

function webRepoUrl(connection: ConnectionLike, owner: string, repo: string): string {
  if (connection.provider === "github") return `https://github.com/${owner}/${repo}`;
  if (connection.provider === "gitlab" || connection.provider === "gitlab_self_hosted") return `${connection.endpoint || "https://gitlab.com"}/${owner}/${repo}`;
  return `https://bitbucket.org/${owner}/${repo}`;
}

function summarizeSeverity(severity: string): string {
  const normalized = severity.toLowerCase();
  if (normalized.includes("critical")) return "Critical";
  if (normalized.includes("high")) return "High";
  if (normalized.includes("medium")) return "Medium";
  if (normalized.includes("low")) return "Low";
  return "Info";
}

export function summarizeFindingTitle(input: Pick<CreateMergeRequestInput, "severity" | "message" | "filePath">): string {
  const trimmed = input.message.trim();
  const prefix = `[${summarizeSeverity(input.severity)}]`;
  const base = trimmed.length > 72 ? `${trimmed.slice(0, 69)}...` : trimmed;
  return `${prefix} ${base} (${input.filePath})`;
}

export function estimateFixMinutes(input: Pick<CreateMergeRequestInput, "severity" | "snippet" | "startLine" | "endLine">): number {
  const lineSpan = Math.max(1, input.endLine - input.startLine + 1);
  const snippetComplexity = Math.ceil(input.snippet.length / 180);
  const severityMultiplier = input.severity.toLowerCase().includes("critical")
    ? 2.2
    : input.severity.toLowerCase().includes("high")
      ? 1.8
      : input.severity.toLowerCase().includes("medium")
        ? 1.4
        : 1.1;
  return Math.max(10, Math.round((lineSpan * 2 + snippetComplexity * 6) * severityMultiplier));
}

function buildBody(input: CreateMergeRequestInput, fixSummary?: string): string {
  return [
    "## Security finding context",
    `- File: \`${input.filePath}\``,
    `- Range: ${input.startLine}-${input.endLine}`,
    `- Rule: \`${input.ruleId}\``,
    `- Severity: ${input.severity}`,
    "",
    "## Finding message",
    input.message,
    "",
    fixSummary ? `## Fix summary\n${fixSummary}\n` : "",
    "## Code snippet",
    "```",
    input.snippet || "// snippet unavailable",
    "```",
    "",
    "This merge request was generated by Dockier's AI remediation workflow.",
  ].join("\n");
}

async function createProviderMergeRequest(
  connection: ConnectionLike,
  input: CreateMergeRequestInput,
  sourceBranch: string,
  targetBranch: string,
  title: string,
  fixSummary?: string,
): Promise<MergeRequestResult> {
  const body = buildBody(input, fixSummary);

  if (connection.provider === "github") {
    const headers = {
      Authorization: `Bearer ${connection.personal_token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    };
    const origin = baseUrl(connection);
    const createRes = await fetch(`${origin}/repos/${input.owner}/${input.repo}/pulls`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        title,
        head: sourceBranch,
        base: targetBranch,
        body,
        draft: false,
      }),
    });

    if (createRes.ok) {
      const responseBody = (await createRes.json()) as { html_url?: string; node_id?: string; number?: number };
      return {
        mrUrl: responseBody.html_url || `${webRepoUrl(connection, input.owner, input.repo)}/pulls`,
        mrId: responseBody.node_id || String(responseBody.number || ""),
        mrTitle: title,
      };
    }

    const err = (await createRes.json().catch(() => ({}))) as { message?: string };
    throw new DomainError(err.message || `Failed to create pull request (${createRes.status})`, "bad_request");
  }

  if (connection.provider === "gitlab" || connection.provider === "gitlab_self_hosted") {
    const project = encodeURIComponent(`${input.owner}/${input.repo}`);
    const headers = { "PRIVATE-TOKEN": connection.personal_token, "Content-Type": "application/json" };
    const origin = baseUrl(connection);
    const response = await fetch(`${origin}/api/v4/projects/${project}/merge_requests`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        source_branch: sourceBranch,
        target_branch: targetBranch,
        title,
        description: body,
        assignee_id: input.assignee ? Number(input.assignee) : undefined,
        reviewer_ids: input.reviewer ? [Number(input.reviewer)] : undefined,
      }),
    });
    if (response.ok) {
      const responseBody = (await response.json()) as { web_url?: string; iid?: number; id?: number };
      return {
        mrUrl: responseBody.web_url || `${webRepoUrl(connection, input.owner, input.repo)}/-/merge_requests`,
        mrId: String(responseBody.iid || responseBody.id || ""),
        mrTitle: title,
      };
    }
    const err = (await response.json().catch(() => ({}))) as { message?: string };
    throw new DomainError(err.message || `Failed to create merge request (${response.status})`, "bad_request");
  }

  throw new DomainError(`AI fix merge requests are not supported for provider: ${connection.provider}`, "bad_request");
}

async function createAiFixMergeRequest(
  connection: ConnectionLike,
  input: CreateMergeRequestInput,
  options: CreateMergeRequestOptions,
): Promise<MergeRequestResult> {
  if (!options.openAiApiKey) {
    throw new DomainError("OpenAI API key is not configured", "precondition_failed");
  }

  const fileContent = await fetchRepoFile(connection, {
    owner: input.owner,
    repo: input.repo,
    branch: input.branch,
  }, input.filePath);
  if (!fileContent) {
    throw new DomainError(`Could not read ${input.filePath} from ${input.branch}`, "not_found");
  }

  const fix = await generateCodeFix(options.openAiApiKey, options.openAiModel || "gpt-4o-mini", {
    filePath: input.filePath,
    fileContent,
    startLine: input.startLine,
    endLine: input.endLine,
    ruleId: input.ruleId,
    severity: input.severity,
    message: input.message,
    snippet: input.snippet,
  });

  const title = summarizeFindingTitle(input);
  const commitMessage = `fix(security): ${title}\n\n${fix.summary}`;
  const { fixBranch, targetBranch } = await commitFixToBranch(connection, {
    owner: input.owner,
    repo: input.repo,
    baseBranch: input.branch,
    filePath: input.filePath,
    fixedContent: fix.fixedContent,
    commitMessage,
    ruleId: input.ruleId,
  });

  return createProviderMergeRequest(connection, input, fixBranch, targetBranch, title, fix.summary);
}

export async function createMergeRequest(
  connection: ConnectionLike,
  input: CreateMergeRequestInput,
  options: CreateMergeRequestOptions = {},
): Promise<MergeRequestResult> {
  if (input.aiType) {
    return createAiFixMergeRequest(connection, input, options);
  }

  const title = summarizeFindingTitle(input);
  const targetBranch = input.branch;
  return createProviderMergeRequest(connection, input, input.branch, targetBranch, title);
}
