-- Allow deployments without a git connection (e.g. template-based deploys like WordPress).
-- Drop the NOT NULL constraint and foreign key, then re-add FK as nullable.

ALTER TABLE deployments ALTER COLUMN git_connection_id DROP NOT NULL;
ALTER TABLE deployments ALTER COLUMN git_connection_id SET DEFAULT NULL;

-- Drop existing FK constraint (name is auto-generated by Postgres)
ALTER TABLE deployments DROP CONSTRAINT IF EXISTS deployments_git_connection_id_fkey;

-- Re-add as nullable FK (NULL values bypass the constraint)
ALTER TABLE deployments
  ADD CONSTRAINT deployments_git_connection_id_fkey
  FOREIGN KEY (git_connection_id) REFERENCES git_connections(id);
