import { api, APIError } from "encore.dev/api";
import { db, BedrockApiKey, BedrockRegion, BedrockAccountId } from "../shared";
import { throwProviderError } from "../helpers";

// ─── Helper: call AI to generate fix ───

async function generateAIFix(aiType: string, aiConfig: Record<string, string>, filePath: string, fileContent: string, finding: { ruleId: string; severity: string; message: string; snippet: string; startLine: number; endLine: number }): Promise<string> {
  const prompt = `You are a senior security engineer. Fix the following security vulnerability in the code.

**File:** \`${filePath}\`
**Rule:** \`${finding.ruleId}\`
**Severity:** ${finding.severity}
**Issue:** ${finding.message}
**Lines:** ${finding.startLine}–${finding.endLine}

**Vulnerable code snippet:**
\`\`\`
${finding.snippet}
\`\`\`

**Full file content:**
\`\`\`
${fileContent}
\`\`\`

Instructions:
1. Fix ONLY the security vulnerability described above.
2. Keep all existing functionality, imports, and code structure intact.
3. Return the COMPLETE fixed file content — every line, not just the changed part.
4. Do NOT include markdown fences, explanations, or commentary — output raw file content only.`;

  // Amazon Bedrock — Bearer auth with API key from Encore secret
  const apiKey = BedrockApiKey();
  if (!apiKey) throw new Error("BedrockApiKey secret is not configured");
  const region = BedrockRegion() || "us-east-1";
  const modelId = aiConfig.model || "us.anthropic.claude-sonnet-4-20250514-v1:0";
  const accountId = BedrockAccountId() || "";
  const modelArn = modelId.startsWith("arn:") ? modelId : `arn:aws:bedrock:${region}:${accountId}:inference-profile/${modelId}`;
  const url = `https://bedrock-runtime.${region}.amazonaws.com/model/${encodeURIComponent(modelArn)}/converse`;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      messages: [{ role: "user", content: [{ text: prompt }] }],
      inferenceConfig: { temperature: 0.2, maxTokens: 32000 },
    }),
  });
  if (!res.ok) {
    const errBody: any = await res.json().catch(() => ({}));
    throw new Error(`Bedrock ${res.status}: ${errBody.message || errBody.Message || res.statusText}`);
  }
  const data: any = await res.json();
  const raw = data.output?.message?.content?.[0]?.text?.trim() || "";
  return raw.replace(/^```[\w]*\n?/, "").replace(/\n?```$/, "").trim();
}

// ─── Create PR/MR with AI Fix ───

export const createFixMR = api(
  { method: "POST", path: "/git/connections/:connectionId/create-mr", auth: true },
  async (params: {
    connectionId: string;
    owner: string;
    repo: string;
    branch: string;
    filePath: string;
    startLine: number;
    endLine: number;
    ruleId: string;
    severity: string;
    message: string;
    snippet: string;
    aiType?: string;
    aiConfig?: Record<string, string>;
  }): Promise<{ mrUrl: string; mrId: string; mrTitle: string }> => {
    const conn = await db.queryRow<{
      provider: string; personal_token: string; endpoint: string;
    }>`SELECT provider, personal_token, endpoint FROM git_connections WHERE id = ${params.connectionId}`;

    if (!conn) throw APIError.notFound("Connection not found");

    const fixBranch = `fix/${params.ruleId.replace(/[^a-zA-Z0-9._-]/g, "-")}-${Date.now()}`;
    const title = `Fix: [${params.severity.toUpperCase()}] ${params.message.substring(0, 80)}`;
    const hasAI = !!params.aiType;

    const bodyParts = [
      `## Security Fix`,
      ``,
      `**Rule:** \`${params.ruleId}\``,
      `**Severity:** ${params.severity}`,
      `**File:** \`${params.filePath}\` (L${params.startLine}–L${params.endLine})`,
      ``,
      `**Finding:** ${params.message}`,
      ``,
      params.snippet ? `\`\`\`\n${params.snippet}\n\`\`\`` : "",
      ``,
      `---`,
      hasAI ? `*Fix generated by AI (${params.aiType}) from security scan*` : `*Created automatically from security scan*`,
    ];
    const body = bodyParts.filter(Boolean).join("\n");

    if (conn.provider === "github") {
      const baseUrl = conn.endpoint || "https://api.github.com";
      const headers = { Authorization: `Bearer ${conn.personal_token}`, Accept: "application/vnd.github.v3+json", "Content-Type": "application/json" };

      // Get the SHA of the source branch
      const refRes = await fetch(`${baseUrl}/repos/${params.owner}/${params.repo}/git/ref/heads/${encodeURIComponent(params.branch)}`, { headers });
      if (!refRes.ok) throw APIError.internal("Could not get branch ref");
      const refData = await refRes.json() as any;
      const sha = refData.object?.sha;

      // Create the fix branch
      const createRefRes = await fetch(`${baseUrl}/repos/${params.owner}/${params.repo}/git/refs`, {
        method: "POST", headers,
        body: JSON.stringify({ ref: `refs/heads/${fixBranch}`, sha }),
      });
      if (!createRefRes.ok) {
        const err = await createRefRes.json().catch(() => ({})) as any;
        throw APIError.internal(`Failed to create branch: ${err.message || createRefRes.statusText}`);
      }

      // If AI is available, fetch file, generate fix, and commit
      if (hasAI) {
        // Get file content
        const fileRes = await fetch(`${baseUrl}/repos/${params.owner}/${params.repo}/contents/${encodeURIComponent(params.filePath)}?ref=${encodeURIComponent(fixBranch)}`, { headers });
        if (fileRes.ok) {
          const fileData = await fileRes.json() as any;
          const originalContent = Buffer.from(fileData.content || "", "base64").toString("utf-8");
          const fixedContent = await generateAIFix(params.aiType!, params.aiConfig!, params.filePath, originalContent, params);
          if (fixedContent && fixedContent !== originalContent) {
            // Commit the fix
            await fetch(`${baseUrl}/repos/${params.owner}/${params.repo}/contents/${encodeURIComponent(params.filePath)}`, {
              method: "PUT", headers,
              body: JSON.stringify({
                message: `fix: ${params.ruleId} — ${params.message.substring(0, 60)}`,
                content: Buffer.from(fixedContent).toString("base64"),
                sha: fileData.sha,
                branch: fixBranch,
              }),
            });
          }
        }
      }

      // Create the PR
      const prRes = await fetch(`${baseUrl}/repos/${params.owner}/${params.repo}/pulls`, {
        method: "POST", headers,
        body: JSON.stringify({ title, body, head: fixBranch, base: params.branch }),
      });
      if (!prRes.ok) {
        const err = await prRes.json().catch(() => ({})) as any;
        throw APIError.internal(`Failed to create PR: ${err.message || prRes.statusText}`);
      }
      const pr = await prRes.json() as any;
      return { mrUrl: pr.html_url || "", mrId: String(pr.number || pr.id), mrTitle: title };

    } else if (conn.provider === "gitlab" || conn.provider === "gitlab_self_hosted") {
      const baseUrl = conn.endpoint || "https://gitlab.com";
      const headers: Record<string, string> = { "PRIVATE-TOKEN": conn.personal_token, "Content-Type": "application/json" };
      const projectPath = encodeURIComponent(`${params.owner}/${params.repo}`);

      // Verify project exists first
      const projectCheck = await fetch(`${baseUrl}/api/v4/projects/${projectPath}`, { headers });
      if (!projectCheck.ok) {
        // Try URL-encoding with just the repo name (no owner) in case it's a flat namespace
        const altPath = encodeURIComponent(params.repo);
        const altCheck = await fetch(`${baseUrl}/api/v4/projects/${altPath}`, { headers });
        if (!altCheck.ok) {
          throw APIError.notFound(`GitLab project not found: ${params.owner}/${params.repo} (tried both encoded paths). Check the repository URL and token permissions.`);
        }
      }

      // Create the fix branch
      const branchRes = await fetch(`${baseUrl}/api/v4/projects/${projectPath}/repository/branches`, {
        method: "POST", headers,
        body: JSON.stringify({ branch: fixBranch, ref: params.branch }),
      });
      if (!branchRes.ok) {
        const err = await branchRes.json().catch(() => ({})) as any;
        throw APIError.internal(`Failed to create branch: ${err.message || err.error || branchRes.statusText}`);
      }

      // If AI is available, fetch file, generate fix, and commit
      if (hasAI) {
        const fileRes = await fetch(`${baseUrl}/api/v4/projects/${projectPath}/repository/files/${encodeURIComponent(params.filePath)}?ref=${encodeURIComponent(fixBranch)}`, { headers });
        if (fileRes.ok) {
          const fileData = await fileRes.json() as any;
          const originalContent = Buffer.from(fileData.content || "", "base64").toString("utf-8");
          const fixedContent = await generateAIFix(params.aiType!, params.aiConfig!, params.filePath, originalContent, params);
          if (fixedContent && fixedContent !== originalContent) {
            await fetch(`${baseUrl}/api/v4/projects/${projectPath}/repository/files/${encodeURIComponent(params.filePath)}`, {
              method: "PUT", headers,
              body: JSON.stringify({
                branch: fixBranch,
                commit_message: `fix: ${params.ruleId} — ${params.message.substring(0, 60)}`,
                content: fixedContent,
                encoding: "text",
              }),
            });
          }
        }
      }

      // Create the MR
      const mrRes = await fetch(`${baseUrl}/api/v4/projects/${projectPath}/merge_requests`, {
        method: "POST", headers,
        body: JSON.stringify({ source_branch: fixBranch, target_branch: params.branch, title, description: body }),
      });
      if (!mrRes.ok) {
        const err = await mrRes.json().catch(() => ({})) as any;
        throw APIError.internal(`Failed to create MR: ${err.message || err.error || mrRes.statusText}`);
      }
      const mr = await mrRes.json() as any;
      return { mrUrl: mr.web_url || "", mrId: String(mr.iid || mr.id), mrTitle: title };

    } else if (conn.provider === "bitbucket") {
      const baseUrl = conn.endpoint || "https://api.bitbucket.org";
      const headers = { Authorization: `Bearer ${conn.personal_token}`, "Content-Type": "application/json" };

      // Create the fix branch
      const branchRes = await fetch(`${baseUrl}/2.0/repositories/${params.owner}/${params.repo}/refs/branches`, {
        method: "POST", headers,
        body: JSON.stringify({ name: fixBranch, target: { hash: params.branch } }),
      });
      if (!branchRes.ok) {
        const err = await branchRes.json().catch(() => ({})) as any;
        throw APIError.internal(`Failed to create branch: ${err.error?.message || branchRes.statusText}`);
      }

      // Create the PR
      const prRes = await fetch(`${baseUrl}/2.0/repositories/${params.owner}/${params.repo}/pullrequests`, {
        method: "POST", headers,
        body: JSON.stringify({
          title, description: body,
          source: { branch: { name: fixBranch } },
          destination: { branch: { name: params.branch } },
        }),
      });
      if (!prRes.ok) {
        const err = await prRes.json().catch(() => ({})) as any;
        throw APIError.internal(`Failed to create PR: ${err.error?.message || prRes.statusText}`);
      }
      const pr = await prRes.json() as any;
      return { mrUrl: pr.links?.html?.href || "", mrId: String(pr.id), mrTitle: title };
    }

    throw APIError.unimplemented("PR/MR creation not supported for this provider");
  }
);

// ─── Bedrock Model Listing ───

export const listBedrockModels = api(
  { method: "GET", path: "/git/bedrock/models", auth: true },
  async (): Promise<{ models: Array<{ id: string; name: string }> }> => {
    const apiKey = BedrockApiKey();
    if (!apiKey) throw APIError.failedPrecondition("BedrockApiKey secret is not configured");
    const region = BedrockRegion() || "us-east-1";
    const accountId = BedrockAccountId() || "";

    // List inference profiles — these are what you actually invoke
    const profilesRes = await fetch(`https://bedrock.${region}.amazonaws.com/inference-profiles`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    if (profilesRes.ok) {
      const profilesData: any = await profilesRes.json();
      const profiles = (profilesData.inferenceProfileSummaries || [])
        .filter((p: any) => p.type === "SYSTEM_DEFINED" && p.status === "ACTIVE")
        .map((p: any) => ({
          id: p.inferenceProfileId || p.inferenceProfileArn,
          name: p.inferenceProfileName || p.inferenceProfileId,
        }))
        .sort((a: any, b: any) => a.name.localeCompare(b.name));
      if (profiles.length > 0) return { models: profiles };
    }

    // Fallback: list foundation models and build ARNs
    const res = await fetch(`https://bedrock.${region}.amazonaws.com/foundation-models`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    if (!res.ok) {
      const err: any = await res.json().catch(() => ({}));
      throw APIError.internal(err?.message || err?.Message || `Bedrock API error: ${res.status}`);
    }
    const data: any = await res.json();
    const models = (data.modelSummaries || [])
      .filter((m: any) => m.inferenceTypesSupported?.includes("ON_DEMAND") && m.outputModalities?.includes("TEXT"))
      .map((m: any) => ({
        id: m.modelId,
        name: `${m.providerName} — ${m.modelName}`,
      }))
      .sort((a: any, b: any) => a.name.localeCompare(b.name));
    return { models };
  }
);
